Fix issue with missing duration
python process_cowrie.py --summarizedays 2
2026-08-24 15:21:49,768:INFO:root:process_cowrie.py:initialize_database:Database initializing...
Failure adding table columns, likely because they already exist...
2026-08-24 15:21:49,890:ERROR:root:process_cowrie.py:initialize_database:Failure adding table columns, likely because they already exist...
2026-08-24 15:21:49,891:ERROR:root:process_cowrie.py:initialize_database:Failure adding table columns, likely because they already exist...
Days to summarize: 2
Processing file /srv/cowrie/var/log/cowrie/cowrie.json
2026-08-24 15:21:49,892:INFO:root:process_cowrie.py:get_session_id:Extracting unique sessions
2026-08-24 15:21:49,892:INFO:root:process_cowrie.py:get_protocol_login:Getting protocol from session connection...
2026-08-24 15:21:49,892:INFO:root:process_cowrie.py:get_session_duration:Getting session durations...
Traceback (most recent call last):
  File "/home/honeypotuser/temp/process_cowrie.py", line 1221, in <module>
    print_session_info(data, session_id, "standard")
    ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/honeypotuser/temp/process_cowrie.py", line 655, in print_session_info
    session_duration = get_session_duration(session, data)
  File "/home/honeypotuser/temp/process_cowrie.py", line 300, in get_session_duration
    duration = each_entry['duration']
               ~~~~~~~~~~^^^^^^^^^^^^
KeyError: 'duration'