fixed issue when only using 'logpath' option
data needed to be summarized when only using logpath option to feed session data

Processing file /home/cowrie/cowrie/var/log/cowrie/cowrie.json
Traceback (most recent call last):
File "/home/cowrie/cowrieprocessor/process_cowrie.py", line 626, in
summarystring += "{:>40s} {:10s}".format("Most Common Number of Commands:", str(number_of_commands[0])) + "\n"
IndexError: list index out of range